openapi: 3.1.0
info:
  title: RAG Files API
  version: 1.0.0
  description: Simple per-file RAG API for ChatGPT Actions. Wraps your local LangChain+Chroma RAG.
  termsOfService: https://kcgmhrt-acbc4e82a7da.herokuapp.com/terms
servers:
  # 佈署後請將此 URL 改成你的 Heroku 網址
  - url: https://kcgmhrt-acbc4e82a7da.herokuapp.com
    description: Heroku deployment
security:
  - bearerAuth: []
paths:
  /health:
    get:
      operationId: health
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  openai_key:
                    type: boolean
                    description: Whether OPENAI_API_KEY is present on server
  /files:
    get:
      operationId: listFiles
      summary: List available documents
      description: |
        Use this before calling queryFile when the user has not specified a file.
        Present the list to the user and ask them to choose one exact filename.
        Do not guess the file; wait for the user to confirm.
      responses:
        "200":
          description: A list of filenames under docs/
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /query:
    post:
      operationId: queryFile
      summary: Ask a question against a specific file
      description: |
        Requires an explicit `file` chosen from `GET /files`. If the user did not
        specify a file, first call `listFiles`, show the options, and ask the user
        to choose one exact filename. Do not guess. Answer with cited `sources`.
        If the user speaks Chinese, reply in zh-TW.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [file, question]
              properties:
                file:
                  type: string
                  description: Filename under docs/. Must be one of the values returned by GET /files.
                question:
                  type: string
                  description: User question
                top_k:
                  type: integer
                  minimum: 1
                  maximum: 10
                  default: 3
            examples:
              askExample:
                summary: Simple question
                value:
                  file: example.pdf
                  question: 請用重點條列摘要這份文件
                  top_k: 3
      responses:
        "200":
          description: Answer with sources
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  sources:
                    type: array
                    items:
                      type: string
              examples:
                answerExample:
                  value:
                    answer: 這份文件主要說明 A/B/C 三點…
                    sources: [example.pdf]
  /reload:
    post:
      operationId: reloadIndex
      summary: Force rebuild index for a file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
      responses:
        "200":
          description: Rebuilt
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: reloaded
                  file:
                    type: string
                    example: example.pdf
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
